version: '3.8'

services:
  db:
    container_name: shareit-db-container
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=postgres
    image: postgres:13.7-alpine
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/

  server:
    build: ./server
    container_name: shareit-server-container
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SERVER_PORT=9090
    image: server
    ports:
      - "9090"

  gateway:
    build: ./gateway
    container_name: shareit-gateway-container
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:9090
    image: gateway
    ports:
      - "8080:8080"