version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build: ./server
    ports:
      - "9091:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server